# Generated by Django 2.1.2 on 2018-10-25 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='dog_image')),
                ('name', models.CharField(max_length=30)),
                ('race', models.CharField(max_length=30)),
                ('description', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=10)),
            ],
        ),
    ]
