# Generated by Django 2.1.2 on 2018-10-25 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adopcion', '0002_auto_20181025_1745'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dog',
            name='state',
            field=models.CharField(choices=[('Rescatado', 'Rescatado'), ('Disponible', 'Disponible'), ('Adoptado', 'Adoptado')], default='Rescatado', max_length=10),
        ),
    ]
