# Generated by Django 2.1.2 on 2018-10-26 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adopcion', '0004_adoptionregister'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adoptionregister',
            name='owner',
            field=models.CharField(max_length=30),
        ),
    ]
